name: Firebase Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        env:
          CI: false
        run: |
          touch .env
          echo REACT_APP_EMAILJS_SERVICE_ID= ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}  >> .env
          echo REACT_APP_EMAILJS_TEMPLATE_ID= ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}  >> .env 
          echo REACT_APP_EMAILJS_USER_ID= ${{ secrets.REACT_APP_EMAILJS_USER_ID }}  >> .env

          cat .env
          npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
